image: ecr.aws.steedos.cn/dockerhub/steedos/gitpod-workspace-base:2.2.2

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
  - port: 27017
    onOpen: ignore
    visibility: public
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: MongoDB
    command: |
      mkdir -p /workspace/mongodb/data/db
      mongod --replSet rs0 --bind_ip_all --dbpath /workspace/mongodb/data/db
  - command: |
      gp await-port 27017
      mongo steedos --eval "rs.initiate();conf = rs.conf();conf.members[0].host=\"127.0.0.1\";rs.reconfig(conf, {force:true});"
      exit
  - name: Redis
    command: |
      redis-server --protected-mode no --save "" --appendonly no --client-output-buffer-limit replica 0 0 0 --client-output-buffer-limit pubsub 0 0 0 --client-output-buffer-limit slave 0 0 0
  - name: Steedos
    init: |
      echo "ROOT_URL=$(gp url 5000)" >> .env.local
      echo "METADATA_SERVER=$(gp url 5000)" >> .env.local
      git config --global pull.rebase false
      yarn global add steedos-cli@next 
    command: |
      yarn install
      gp await-port 27017
      gp await-port 6379
      yarn start

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - redhat.vscode-yaml
    - steedos.steedosdx-vscode
    - steedos.steedosdx-vscode-core
    - ms-ceintl.vscode-language-pack-zh-hans