version: "3.9"

services:

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    command: --replSet steedos
    healthcheck:
      test: echo 'rs.initiate(); db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongo-data:/data/db'

volumes:
  steedos-mongo-data:
    driver: local