version: "3"

services:
  steedos:
    image: steedos/steedos-apps:2.1.2.1
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "./storage:/app/storage"
      - "./.env.local:/app/.env.local"