version: "3.9"

services:

  steedos:
    image: steedos/steedos-community:2.4
    ports:
      - "5000:5000"
    env_file:
      - .env.local
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/steedos
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - TRANSPORTER=nats://nats:4222
      - CACHER=redis://redis:6379
    depends_on:
      mongodb:
        condition: service_healthy