version: "3"

services:
  steedos:
    image: steedos/steedos-project-template-codeserver:0.0.1
    restart: always
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - "./storage:/app/storage"
      - "./.env.local:/app/.env.local"